// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const datasource = {
  url: env("DIRECT_URL"),
  directUrl: env("DIRECT_URL"),
} as unknown as {
  url: string;
  directUrl?: string;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource,
});
